###
GET http://localhost:8080/animal

### Sign up
< {%
    request.variables.set("username", "konrad")
    request.variables.set("password", "pass")
%}
POST http://localhost:8080/signup
Content-Type: application/json

{
  "firstName": "Konrad",
  "lastName": "Kowalski",
  "username":  "{{username}}",
  "password": "{{password}}"
}
> {%
    client.global.set("auth_token", response.body.token)
%}

### Login
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "konrad",
  "password": "pass"
}
> {%
    client.global.set("auth_token", response.body.token)
%}

### Get all Users
GET http://localhost:8080/users?page=0&size=10&sort=wow,desc
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get all Projects
GET http://localhost:8080/projects?page=0&per_page=5&sort=id&direction=asc
Accept: application/json
Authorization: Bearer {{auth_token}}

### Create a Project
POST http://localhost:8080/projects
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "projectName": "Example project 10"
}

### Get all Project Issues
GET http://localhost:8080/projects/2/issues

### Create an Issue
POST http://localhost:8080/issues
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "My issue 1",
  "description": "Example description 1",
  "projectId": 1,
  "assigneeUsername": "konrad"
}

###

PATCH http://localhost:8080/projects/
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": 3,
  "name": "awooooo"
}

###

