### Sign up
< {%
    request.variables.set("username", "konrad")
    request.variables.set("password", "pass")
%}
POST http://localhost:8080/signup
Content-Type: application/json

{
  "firstName": "Konrad",
  "lastName": "Konrad",
  "username":  "{{username}}",
  "password": "{{password}}"
}
> {%
    client.global.set("auth_token", response.body.token)
%}

### Login
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "konrad",
  "password": "pass"
}
> {%
    client.global.set("auth_token", response.body.token)
%}

### Get all projects
GET http://localhost:8080/projects?page=0&per_page=10&direction=asc
Accept: application/json
Authorization: Bearer {{auth_token}}

### Create a project
POST http://localhost:8080/projects
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "projectName": "Example project 3"
}

###
GET http://localhost:8080/data
Accept: application/json

###
POST http://localhost:8080/api/item
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="field-name"; filename="file.txt"

< ./relative/path/to/local_file.txt
--WebAppBoundary--
