myapp:
  # TODO
  jwtKey: hi

spring:
#  devtools:
#    add-properties: false

  h2:
    console:
      enabled: true

  liquibase:
    enabled: false

  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
  #    url: 'jdbc:postgresql://vps626754.ovh.net/mydb'
  #    username: postgres
  #    password: asyncsupportconfigurer

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        highlight_sql: true
#        generate_statistics: true
#        use_sql_comments: true
        format_sql: true
    open-in-view: false
#    generate-ddl: true



server:
  error:
    include-stacktrace: never # The field "trace" with stacktrace is present if you have spring-boot-devtools in your classpath
    include-message: always
#  error:
#    whitelabel:
#      enabled: false

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging:
              ConditionEvaluationReportLogger: info # Suppress conditions evaluation report
    sql: debug
#    root: fatal
