myapp:
  jwtKey: hi # TODO

spring:
  devtools:
    restart:
      quiet-period: 2000
      poll-interval: 2001
#      add-properties: false
  h2:
    console:
      enabled: true
  liquibase:
    enabled: false
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
#        url: 'jdbc:postgresql://vps626754.ovh.net/mydb'
#        username: postgres
#        password: asyncsupportconfigurer
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        highlight_sql: true
        #        generate_statistics: true
        #        use_sql_comments: true
    #        format_sql: true
    open-in-view: false
  #    generate-ddl: true
  data:
    web:
      pageable:
        max-page-size: 40 # TODO

server:
  error:
    include-stacktrace: never # The field "trace" with stacktrace is present if you have spring-boot-devtools in your classpath
    include-message: always
#  error:
#    whitelabel:
#      enabled: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        engine:
          transaction: DEBUG
        orm:
          jdbc:
            bind: trace
#            extract: trace
        type: trace
      springframework:
        orm:
          jpa: DEBUG
        transaction: DEBUG
        transaction.interceptor: TRACE
        boot:
          autoconfigure:
            logging:
              ConditionEvaluationReportLogger: info # Suppress conditions evaluation report
    sql: debug
#    root: trace
  pattern:
    dateformat: HH:mm:ss.SSS
#    root: fatal
